spring.application.name=proyectoFinal
spring.config.import=optional:file:../.env[.properties],optional:file:.env[.properties]

# Database Configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=false

# JWT Configuration
jwt.secret=${JWT_SECRET}

# Directory
dir.images.movie=${MOVIE_DIR}
dir.images.user=${USER_DIR}